### PR TITLE
mwaga is a shit leader, he ruins Warsow

### PR DESCRIPTION
**Pull request by mazocomp**
mwaga is @dnk777 if you don't know.

### CODE REVIEW

**Comment by mazocomp** [comment]
This is a fork of qfusion developed by asshole mwaga which refuses to cooperate to make Warsow cross-platform by calling it ["minor topic that has nothing with actual challenges in the game development"](https://github.com/Warsow/qfusion/pull/40#issuecomment-492069962). The goal of this fork is to ruin Warsow by making it more crappy. See for yourself any file, you will notice shit code instantly.

**Comment by mazocomp** [comment]
Note that I only wallhacked in the past, that's not a reason to not cooperate.

**Comment by mazocomp** [comment]
From mazocomp@disroot.org Sat Jun  8 18:26:02 2019
Date: Sat, 8 Jun 2019 18:26:02 +0300
From: Leonid Bobrov <mazocomp@disroot.org>
To: mwagawsw@gmail.com
Subject: Answer me: why are you an asshole developer?
Message-ID: <20190608152600.GA66483@mazocomp.lan>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
User-Agent: Mutt/1.12.0 (2019-05-25)
Status: RO
Content-Length: 626
Lines: 11

Hey, you moron. Why do you call cross-platformability "minor topic that
has nothing with actual challenges in the game development"? You prefer
being asshole intentionally not allowing to run Warsow at systems other
than Windows and Linux? What kind of open source project are you then?
You are shit leader. May Warsow never be released again, you only ruin
this game. This game already was a crap, but you only made it worse. And
what's the story behind CEF/Chromium binaries? Is that a way to show
middle finger to everyone?

Also about cheats: fuck you, you moral idiot, that's not the reason to
not accept patches I send.

**Comment by stylemistake** [comment]
If i remember correctly, your patches involved disabling pure checks, which only makes it easier to write cheats, so personally idk, but mwaga seems reasonable here to decline them. But I do think he went a bit too personal.

**Pull request closed without merging**
